### ISSUE TITLE
May be add a write-barrier about dot character

### ISSUE THREAD

**Issue by dinosaure** [mirage/colombe#29] opened 2020-11-20 12:48 UTC
Currently, `colombe` does not check if the user sends `.` or not - and finish on its way, the email. It can lead errors if the user does not care/are aware about that so we probably need to check and translate `.\r\n` to `..\r\n` according RFC 5321 here:

https://github.com/mirage/colombe/blob/da2281afa60cf906405120f647d8c247d189cb85/sendmail/sendmail.ml#L236

@Julow, I know that you got this issue one time, what do you think? Then, @jerben gently asked me about that. Even if the documentation mentions that we send the given email as is:

https://github.com/mirage/colombe/blob/da2281afa60cf906405120f647d8c247d189cb85/sendmail/sendmail_lwt.mli#L67-L69

It's not clear and well understandable that error can occur if the user send `.\r\n`

**Comment by Julow** [comment] 2020-11-20 13:29
I fell for this indeed but the root cause was that I tried not to use `mrmime` (I guess, for doing thing step by step but it ended up being a lot of debugging).
I think it'll be reasonable to ensure that inputs can't interfere with the protocol (escaping problematic lines and inserting the terminator). Maybe that logic can be removed from mrmime and moved into colombe ?

**Comment by dinosaure** [comment] 2020-11-20 13:42
> Maybe that logic can be removed from mrmime and moved into colombe ?

Hmmhmm, I think `mrmime` does not handle such case. I can not find an occurrence of such proxy in my code. In anyway, I think the best is to add that into `colombe` which already handles the terminator by itself.

**Comment by jerben** [comment] 2020-11-20 15:11
Hey!

So the problem I am experiencing I think is related but a different one: Creating a plain text email with the body `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaa` with `mrmime` and sending it with `colombe` yields an email received with the content ``aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (the dot is dropped).

According to https://tools.ietf.org/html/rfc5321#section-4.5.2 this can be fixed by doing this: `Before sending a line of mail text, the SMTP client checks the first character of the line.  If it is a period, one additional period is inserted at the beginning of the line.`

**Comment by jerben** [comment] 2020-11-20 15:16
In a private discussion @mikonieminen said:

I did some experiments with letters and verified that this seems to be inside colombe. mrmime generates correctly an email:
````
Subject: line wrapping causing new line to start with .
Date: Fri, 20 Nov 2020 13:55:18 GMT
From: harry@example.com
To: dave@example.com
Cc: 
Content-Type: multipart/alternative; boundary=blaablaa

--blaablaa
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=
.aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

--blaablaa
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=0A<p>Hi=20there,</p>=0A<p>=0A=20=20have=20you=20already=20seen=20the=20ver=
y=20cool=20new=20web=20framework=20foo:=0A=20=20<a=20href=3D"https://github=
.com/oxidizing/sihl">Sihl</a>=0A<p>=0ARegards,<br>=0AThe.=20team=0A</p>=0A

--blaablaa--
```

and when using mailtrap.io those full stops that are starting couple of the lines are now missing:

```
Subject: Mixed body email with plain text and HTML
Date: Fri, 20 Nov 2020 13:38:56 GMT
From: bcjjnkcj2qu2mdar@ethereal.email
To: harry@example.com, larry@example.com
Cc: bill@example.com
Content-Type: multipart/alternative; boundary="YnF4sBMKDHU="

--YnF4sBMKDHU=
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

--YnF4sBMKDHU=
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=0A<p>Hi=20there,</p>=0A<p>=0A=20=20have=20you=20already=20seen=20the=20ver=
y=20cool=20new=20web=20framework=20foo:=0A=20=20<a=20href=3D"https://github=
com/oxidizing/sihl">Sihl</a>=0A<p>=0ARegards,<br>=0AThe.=20team=0A</p>=0A

--YnF4sBMKDHU=--
```

**Comment by dinosaure** [comment] 2020-11-25 14:12
The error is due to the fact that in any way, a SMTP server will eat the first `.` and we must double it before to send it. I'm working on a pull-request with a proper test.

**Comment by dinosaure** [comment] 2020-11-25 16:03
A PR was opened with a specific design and solution.

**Closed** 2020-11-27 11:01 UTC
